/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrevisoesRouteImport } from './routes/previsoes'
import { Route as DadosIniciaisRouteImport } from './routes/dados-iniciais'
import { Route as IndexRouteImport } from './routes/index'

const PrevisoesRoute = PrevisoesRouteImport.update({
  id: '/previsoes',
  path: '/previsoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosIniciaisRoute = DadosIniciaisRouteImport.update({
  id: '/dados-iniciais',
  path: '/dados-iniciais',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dados-iniciais': typeof DadosIniciaisRoute
  '/previsoes': typeof PrevisoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dados-iniciais': typeof DadosIniciaisRoute
  '/previsoes': typeof PrevisoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dados-iniciais': typeof DadosIniciaisRoute
  '/previsoes': typeof PrevisoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dados-iniciais' | '/previsoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dados-iniciais' | '/previsoes'
  id: '__root__' | '/' | '/dados-iniciais' | '/previsoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DadosIniciaisRoute: typeof DadosIniciaisRoute
  PrevisoesRoute: typeof PrevisoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/previsoes': {
      id: '/previsoes'
      path: '/previsoes'
      fullPath: '/previsoes'
      preLoaderRoute: typeof PrevisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados-iniciais': {
      id: '/dados-iniciais'
      path: '/dados-iniciais'
      fullPath: '/dados-iniciais'
      preLoaderRoute: typeof DadosIniciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DadosIniciaisRoute: DadosIniciaisRoute,
  PrevisoesRoute: PrevisoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
